title: Website to download stock price predictor
description: A starter ML model to predict stock prices!
theme: just-the-docs

url: ttps://lawfink.github.io/API/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
